apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nebula-studio.name" . }}-upload-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistent.storageClassName }}
  storageClassName: {{ .Values.persistent.storageClassName  }}
  {{- end }}
  resources:
    requests:
      {{- if .Values.persistent.size }}
      storage: {{ .Values.persistent.size  }}
      {{- else }}
      storage: 5Gi
      {{- end }}
