replicaCount: 1

image:
  pullPolicy: IfNotPresent
  nebulaStudio:
    name: vesoft/nebula-graph-studio
    version: v3.2.3

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7001
  nodePort: 32701

resources:
  nebulaStudio:

persistent:
  storageClassName: ""
  size: 5Gi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
