name: Auto Cherry Pick
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
   auto-cherry-pick:
    runs-on: [self-hosted, nebula-fast]
    container:
      image: reg.vesoft-inc.com/dashboard/dashboard-dev:centos7
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - name: keep workspace empty  
        run: |
          rm -rf *
      - name: git config set
        env:
          CLOUD_GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          export GOPRIVATE="github.com/vesoft-inc"
      - name: auto cherry pick
        uses: xigongdaEricyang/cherry-pick-robot@with-python
        with:
          pr_label: ^v[0-9]*\.[0-9]*(.[0-9])?-cherry-pick$
          repo_token: ${{ secrets.GITHUB_TOKEN }}
